config/routes.rb
Rails.application.routes.draw do
  root 'developers#index'

  # get 'developers#index'
  # get 'programming_languages#index'
  # get 'interviews#index'

  resources :developers
  resources :programming_languages
  resources :interviews

  namespace :api do
    resources :developers, only: [:index]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_and_belongs_to_many :languages
  has_and_belongs_to_many :programming_languages
  has_many :interviews
  validates_presence_of :email

  # def prepare_pl_statement
  #   self.includes(:programming_languages)
  # end

  # def prepare_l_statement
  #   self.includes(:languages)
  # end

  def can_write programming_language
    programming_languages.collect(&:name).include? programming_language
  end

  def can_speak language
    languages.collect(&:code).include? language
  end

end

app/models/developer_language.rb
class DeveloperLanguage < ApplicationRecord
end

app/models/developer_programming_language.rb
class DeveloperProgrammingLanguage < ApplicationRecord
end

app/models/interview.rb
class Interview < ApplicationRecord
  belongs_to :developer
  
end

app/models/language.rb
class Language < ApplicationRecord
  has_and_belongs_to_many :developers
  validates_presence_of :code

end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
  has_and_belongs_to_many :developers
  validates_presence_of :name
end

app/controllers/api/api_controller.rb
class Api::BaseController < ApplicationController
  include ExceptionHandler
end

app/controllers/api/developer_api.rb
class Api::DevelopersController < Api::BaseController

  # GET /api/developers.json
  def index
     @developers = developer_service.serve
  end

  protected
  def developer_service
    DeveloperService.new(params)
  end

  private
  def dev_params
    params.permit(:id, :programming_langs, :languages)
  end
end

app/controllers/api/developers.rb
class Api::DevelopersController < Api::BaseController

  # GET /api/developers.json
  def index
     @developers = developer_service.serve
  end

  protected
  def developer_service
    DeveloperService.new(params)
  end

  private
  def dev_params
    params.permit(:id, :programming_langs, :languages)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  # provides the more graceful `included` method
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_dev, only: [:show, :destroy]

  def index
    # @response = developer_service.search
    respond_to do |format|
      format.html
      format.json { render json: ::DevelopersDatatable.new(view_context) }
    end
  end

  def show
  end

  def new
    @developer = Developer.new
  end

  def edit
  end

  def destroy
    @developer.destroy
    respond_to do |format|
      format.html { redirect_to developers_url, notice: 'Dev was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def create
    @developer = Developer.new(dev_params)

    respond_to do |format|
      if @developer.save
        format.html { redirect_to @developer, notice: 'Dev was successfully created.' }
        format.json { render :show, status: :created, location: @developer }
      else
        format.html { render :new }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  protected
  def developer_service
    DeveloperService.new(params)
  end

  private
  def set_dev
    @developer = Developer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dev_params
    params.require(:developer).permit(:email)
  end
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  def index
  end

  def create
  end

  def new
    @interview = Interview.new
    @interview.save

    dev = Developer.find(interview_params[:dev])
    @interview.developer = dev

    respond_to do |format|
      format.html { redirect_to developers_url, notice: "Interview was successfully created for #{dev.email}." }
      format.json { head :no_content }
    end
  end

  def interview_params
    params.permit(:dev)
  end
end

app/controllers/programming_languages_controller.rb
class ProgrammingLanguagesController < ApplicationController
  def index
    @programming_languages = pl_service.all_pl
    @not_used = pl_service.class.not_used
  end

  protected
  def pl_service
    ProgrammingLanguageService.new(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developer_helper.rb
module DeveloperHelper
end

app/views/developers/index.html.erb
<html>
  <head>
    <title> You are here, at Developer controller</title>
    <%= render 'layouts/breadcrumb' %>
  </head>

  <body>
    <h1> Developers </h1>

    <!-- Datatable -->
    <%= content_tag :table, role: :datatable, data: { url: developers_path(format: :json)} do %>
      <thead>
        <tr>
          <th>Email</th>
          <th>Programming Languages</th>
          <th>Languages</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
      </tbody>
    <% end %>
    <!-- End datatable -->
  </body>
</html>

app/views/developers/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @developer.email %>
</p>

<p>
  <strong>Programming Language:</strong>
  <%= @developer.programming_languages.collect(&:name).join(', ') %>
</p>

<p>
  <strong>Language:</strong>
  <%= @developer.languages.collect(&:code).join(', ') %>
</p>

<%= link_to 'Back', developers_path %>

app/views/interviews/index.html.erb
<html>
  <head>
    <title> You are here, at Interview controller</title>
    <%= render 'layouts/breadcrumb' %>
  </head>
  <body>
    <h1> TBD </h1>
  </body>
</html>

app/views/layouts/_breadcrumb.html.erb
<nav>
  <ul>
    <li><%= link_to "Developer", developers_path %></li>
    <li><%= link_to "Programming Language", programming_languages_path %></li>
    <li><%= link_to "Interview", interviews_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R5codingexam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/programming_languages/index.html.erb
<html>
  <head>
    <title> You are here, at Programming Language controller</title>
    <%= render 'layouts/breadcrumb' %>
  </head>
  <body>
    <h1> List all programming languages </h1>
    <table>
      <thead>
        <tr>
          <th> ID </th>
          <th> Name </th>
        </tr>
      </thead>

      <tbody>
        <% @programming_languages.each do |pl| %>
        <tr>
          <td> <%= pl.id %> </td>
          <td> <%= pl.name %> </td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <h1> List programming languages that no one used </h1>
    <table>
      <thead>
        <tr>
          <th> ID </th>
          <th> Name </th>
        </tr>
      </thead>

      <tbody>
        <% @not_used.each do |pl| %>
        <tr>
          <td> <%= pl.id %> </td>
          <td> <%= pl.name %> </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </body>
</html>